name: "CI"
on: [push]

jobs:
  ci:
    name: "CI"
    runs-on: ubuntu-latest
    container: springci/spring-boot-ci:2.7.x
    steps:
      - uses: actions/checkout@v2
      - name: "Build"
        run: |
          ./gradlew build -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false --no-daemon -x asciidoctorPdf -x asciidoctor -x asciidoctorMultipage
      - name: "Upload jars"
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: "jars"
          path: "**/*.jar"
      - name: "Upload test results"
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: "build-results"
          path: "**/build/reports"
